### ISSUE TITLE
Node as target

### ISSUE THREAD

**Issue by klasjersevi** [nicholas-wilcox/lit-modal-portal#4]
I'm trying to use a Lit `renderRoot` as target. The renderRoot is essentially a shadow dom or an element and has the type `DocumentFragment | HTMLElement`. These two types both extend the `Node` type.

Would it be possible to broaden the type of the `target` to `Node | string` so that it's possible to use a shadow dom as target? 
It looks like only methods from the Node interface are used, so I'm thinking that it might be possible to change the type of `target`. 

My workaround which works fine currently is to provide the DocumentFragment as HTMLElement, but it feels ugly and unsafe.

Btw, thanks for a very nice cleanup in v0.6.1!

**Comment by nicholas-wilcox** [comment]
You're welcome! I got inspired when you submitted your PR a while ago. I realized there was so much room for improvement by yanking most of it out.

I've published v0.6.2 on NPM, which declares `target` as a `Node` (or `string`, or `Promise`).
